#! /bin/sh
#
# Written by Miquel van Smoorenburg <miquels@cistron.nl>.
# Modified for Debian GNU/Linux by Ian Murdock <imurdock@gnu.ai.mit.edu>
# and Axel Beckert <abe@deuxchevaux.org>.
#
### BEGIN INIT INFO
# Provides:          doord
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start door lock daemon
### END INIT INFO

. /lib/lsb/init-functions

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/doord.py
NAME=doord
DESC="Door lock daemon"

test -x $DAEMON || exit 0

# Include defaults if available
if [ -f /etc/default/doord ] ; then
	. /etc/default/doord
fi

set -e

case "$1" in
  start)
	log_action_begin_msg "Starting $NAME: "
	start-stop-daemon --start --pidfile /var/run/$NAME.pid \
		--name $NAME --exec $DAEMON
	log_action_end_msg $?
	;;
  stop)
	log_action_begin_msg "Stopping $NAME: "
	start-stop-daemon --stop --pidfile /var/run/$NAME.pid \
		--oknodo --name $NAME
	# Give the old process a few seconds to terminate
	sleep 10
	log_action_end_msg $?
	;;
  restart|force-reload)
	$0 stop
	$0 start	
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
